name: Metrics embed
uses: lowlighter/metrics@v3.10
on:
	schedule:
		- cron: $cron-daily
	push:
		branches: [ master ]
jobs:
	github-metrics-personal:
		runs-on: ubuntu-latest
		steps:
			- name: Personal metrics
				if: ${{ success() || failure() }}
				uses: lowlighter/metrics@latest
				with:
					filename: metrics.svg
					token: ${{ secrets.METRICS_TOKEN }}
					committer_token: ${{ secrets.GITHUB_TOKEN }}
					base: header
					plugin_isocalendar: yes

					base: header, repositories
					repositories: 100
					repositories_forks: no
					repositories_affiliations: owner, collaborator
					repositories_skipped: AjaniBilby/ajanibilby

					plugin_languages: yes
					plugin_languages_ignored: html, css, dockerfile, makefile, qmake, lex, cmake, shell, json
					plugin_languages_details: lines, percentage
					plugin_languages_sections: most-used, recently-used
					plugin_languages_indepth: yes
					plugin_languages_limit: 8

					plugin_habits: yes
					plugin_habits_from: 200
					plugin_habits_days: 14
					plugin_habits_facts: yes
					plugin_habits_charts: yes
					plugin_habits_trim: yes
					config_timezone: Australia/Sydney

					plugin_followup: yes
					plugin_followup_sections: repositories, user

					plugin_projects: yes
					plugin_projects_limit: 4
					plugin_projects_descriptions: yes

					plugin_achievements: yes
					plugin_achievements_threshold: B
					plugin_achievements_secrets: yes
					plugin_achievements_ignored: octonaut
					plugin_achievements_limit: 0

					plugin_lines: yes

					plugin_notable: yes
					plugin_notable_repositories: yes
					config_order: base.header, base.repositories, habbits, followup, projects, languages, achievements