name: metrics
on:
  push:
    schedule:
      -cron: "0 0 * * *"
    push:
      branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          base: header, repositories
          repositories: 100
          repositories_forks: no
          repositories_affiliations: owner, collaborator
          repositories_skipped: AjaniBilby/ajanibilby

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_languages: yes
          plugin_languages_ignored: html, css, dockerfile, makefile, qmake, lex, cmake, shell, json
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 500
          plugin_languages_indepth: yes
          plugin_languages_threshold: 0.1%
          plugin_languages_limit: 8

          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Australia/Sydney

          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0

          plugin_lines: yes

          plugin_notable: yes
          plugin_notable_repositories: yes
          config_order: base.header, introduction, base.repositories, habits, followup, languages, achievements, notable